### PR TITLE
CircleCI setup

### PR DESCRIPTION
**Pull request by chloewlin**
Hi @foodie-hackers/foodies! Can someone review this PR for me? 

For this PR, I set up CircleCI and wrote one test to ensure it works as expected. This test works and CircleCI will rebuild my project every time I do a PR unless I add [ci skip] in my commit. 

There is one hanging PR from the fork I created with my personal github <chloewlin>. That CircleCI rebuild with that fork will fail, so I will probably delete that fork soon to avoid confusion.

### CODE REVIEW

**Comment by Allantzhao** [comment]
@chloewlin Hey Chloe! The setup looks good. You mentioned that you wrote 1 test, but I can't seem to find where you wrote that test. I do see on circle ci that this line of code is run:

 run: echo "A first hello"

Is that what the test is referring to?

**Comment by chloewlin** [comment]
No, the test I was referring are the `sum.js` and `sum.test.js` files in the test folder. They're the sample tests from Jest's official website. 

The run: echo 'A first hello' comes from my script in .circleci/config.yml. I followed CircleCI's documentation here https://circleci.com/docs/2.0/hello-world/ and that line is just to ensure that CircleCI works as expected. We've had some problems configuring CircleCI so I kept it simple for now but I can modify the configurations later using this as a reference (https://circleci.com/docs/2.0/configuration-reference/). Let me know if you have any suggestions.

**Comment by Allantzhao** [comment]
Ahh I see, I just wanted to double check that you had a test since sum.js and sum.test.js aren't shown in the pull request here. 

Approved!

-Allan

**Comment by chloewlin** [comment]
Thanks @Allantzhao for checking. I will start adding new unit tests from now on.

**Pull request merged**
